Add CI for Qt6 static

diff --git a/.github/workflows/build-squiggle.yml b/.github/workflows/build-squiggle.yml
--- a/.github/workflows/build-squiggle.yml
+++ b/.github/workflows/build-squiggle.yml
@@ -1,14 +1,14 @@
-name: Build Squiggle (Cross-Platform)
+name: Build unixcaptool (Linux & macOS)
 
 on:
-  # push:
-  workflow_dispatch:
+  push:
+  # workflow_dispatch:
 
 env:
   QT_VERSION: 6.8.0
 
 jobs:
-  build-qt-linux:
+  build-qt-static-linux:
     runs-on: ubuntu-latest
     outputs:
       qt-install-dir: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
@@ -18,91 +18,33 @@ jobs:
 
       - name: Set QT_INSTALL_DIR
         id: set-qt-dir
-        run: echo "qt-install-dir=${{ runner.temp }}/qt-static-linux" >> $GITHUB_OUTPUT
+        run: echo "qt-install-dir=${{ runner.temp }}/qt-static" >> $GITHUB_OUTPUT
 
-      - name: Cache Qt (Linux)
+      - name: Cache Qt (restore/save)
         id: cache-qt
         uses: actions/cache@v4
         with:
           path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
-          key: qt-static-linux-squiggle-${{ env.QT_VERSION }}-${{ hashFiles('.github/actions/build-qt-static/action.yml') }}-v1
+          key: qt-static-linux-${{ env.QT_VERSION }}-${{ runner.os }}-${{ hashFiles('.github/actions/build-qt-static/action.yml') }}-v4
           restore-keys: |
-            qt-static-linux-squiggle-${{ env.QT_VERSION }}-
+            qt-static-linux-${{ env.QT_VERSION }}-${{ runner.os }}-
 
-      - name: Build static Qt (Linux)
+      - name: Build static Qt
         if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
         uses: ./.github/actions/build-qt-static
         with:
           version: ${{ env.QT_VERSION }}
-          configure-args: "-opensource -confirm-license -no-pch -skip qtwebengine -nomake tests -nomake examples"
+          configure-args: "-opensource -confirm-license -no-pch -skip qtwebengine -nomake tests -nomake examples -platform linux-g++"
           dir: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
-          submodules: "qtbase,qtshadertools,qtdeclarative,qttools,qtimageformats"
+          submodules: "qtbase,qtshadertools,qtdeclarative,qttools,qtwayland,qtimageformats"
 
-      - name: Upload Qt install artifact (Linux)
+      - name: Upload Qt install artifact (for transfer to next job)
+        if: always()
         uses: actions/upload-artifact@v4
         with:
           name: "qt-install-linux"
           path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
-  build-qt-windows:
-    runs-on: windows-latest
-    outputs:
-      qt-install-dir: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
-      qt-artifact-name: "qt-install-windows"
-    steps:
-      - uses: actions/checkout@v4
 
-      - name: Set QT_INSTALL_DIR
-        id: set-qt-dir
-        run: |
-          $temp = "${{ runner.temp }}".Replace('\', '/')
-          echo "qt-install-dir=$temp/qt-static-windows" >> $env:GITHUB_OUTPUT
-
-      - name: Cache Qt (Windows)
-        id: cache-qt
-        uses: actions/cache@v4
-        with:
-          path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
-          key: qt-static-windows-${{ env.QT_VERSION }}-modules-core-gui-widgets-imageformats-v1
-          restore-keys: |
-            qt-static-windows-${{ env.QT_VERSION }}-
-
-      - name: Install dependencies (Windows)
-        if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
-        shell: powershell
-        run: |
-          Set-ExecutionPolicy Bypass -Scope Process -Force
-          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
-          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
-          choco install strawberryperl ninja cmake llvm --yes --no-progress
-
-      - name: Setup MSVC environment
-        if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
-        uses: ilammy/msvc-dev-cmd@v1
-        with:
-          arch: x64
-          vsversion: 2022
-
-      - name: Build static Qt from source (Windows)
-        if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
-        shell: bash
-        run: |
-          mkdir -p "${{ steps.set-qt-dir.outputs.qt-install-dir }}/src"
-          cd "${{ steps.set-qt-dir.outputs.qt-install-dir }}/src"
-          git clone https://code.qt.io/qt/qt5.git
-          cd qt5
-          git checkout v${{ env.QT_VERSION }}
-          perl init-repository --module-subset qtbase,qtshadertools,qtdeclarative,qttools,qtimageformats -f
-          mkdir ../build
-          cd ../build
-          ../qt5/configure.bat -static -opensource -confirm-license -no-pch -skip qtwebengine -nomake tests -nomake examples -make libs -cmake-generator Ninja -prefix "${{ steps.set-qt-dir.outputs.qt-install-dir }}"
-          cmake --build . --parallel
-          cmake --install .
-
-      - name: Upload Qt install artifact (Windows)
-        uses: actions/upload-artifact@v4
-        with:
-          name: "qt-install-windows"
-          path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
   build-qt-macos:
     runs-on: macos-latest
     outputs:
@@ -140,127 +82,124 @@ jobs:
           mkdir ../build
           cd ../build
           export LLVM_DIR=$(brew --prefix llvm)
-          ../qt5/configure -static -opensource -confirm-license -no-pch -skip qtwebengine -nomake tests -nomake examples -make libs -prefix ${{ steps.set-qt-dir.outputs.qt-install-dir }} -D LLVM_INSTALL_DIR="${LLVM_DIR}" -DFEATURE_clang=ON -DFEATURE_clangcpp=ON
+          ../qt5/configure -static -opensource -confirm-license -no-pch -skip qtwebengine -nomake tests -nomake examples -prefix ${{ steps.set-qt-dir.outputs.qt-install-dir }} -D LLVM_INSTALL_DIR="${LLVM_DIR}" -DFEATURE_clang=ON -DFEATURE_clangcpp=ON -platform macx-clang -no-framework
           cmake --build . --parallel $(sysctl -n hw.ncpu)
           cmake --install .
+          cd ${{ steps.set-qt-dir.outputs.qt-install-dir }}
+          find . -type f -name "*.prl" | while read -r file; do
+            sed -i '' -e '/^QMAKE_PRL_BUILD_DIR/d' "$file"
+            sed -i '' -E 's| ?[^ ]*\.o||g' "$file"
+          done
 
       - name: Upload Qt install artifact (macOS)
         uses: actions/upload-artifact@v4
         with:
           name: "qt-install-macos"
           path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
-  build-squiggle:
-    needs: [build-qt-linux, build-qt-windows, build-qt-macos]
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        include:
-          - os: ubuntu-latest
-            qt-needs: build-qt-linux
-            platform-plugin: qxcb
-            artifact-name: squiggle-linux
-            binary-path: packages/squiggle/dist/squiggle
-            
-          - os: windows-latest
-            qt-needs: build-qt-windows
-            platform-plugin: qwindows
-            artifact-name: squiggle-windows
-            binary-path: packages/squiggle/dist/squiggle.exe
 
-          - os: macos-latest
-            qt-needs: build-qt-macos
-            platform-plugin: qcocoa
-            artifact-name: squiggle-macos
-            binary-path: packages/squiggle/dist/squiggle
-
+  build-unixcaptool-linux:
+    needs: build-qt-static-linux
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-
-      - name: Set Qt Environment Variables
-        id: set-qt-env
-        shell: bash
-        run: |
-          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
-            echo "QT_INSTALL_DIR=${{ needs.build-qt-linux.outputs.qt-install-dir }}" >> $GITHUB_ENV
-            echo "QT_ARTIFACT_NAME=${{ needs.build-qt-linux.outputs.qt-artifact-name }}" >> $GITHUB_ENV
-          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
-            echo "QT_INSTALL_DIR=${{ needs.build-qt-windows.outputs.qt-install-dir }}" >> $GITHUB_ENV
-            echo "QT_ARTIFACT_NAME=${{ needs.build-qt-windows.outputs.qt-artifact-name }}" >> $GITHUB_ENV
-          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
-            echo "QT_INSTALL_DIR=${{ needs.build-qt-macos.outputs.qt-install-dir }}" >> $GITHUB_ENV
-            echo "QT_ARTIFACT_NAME=${{ needs.build-qt-macos.outputs.qt-artifact-name }}" >> $GITHUB_ENV
-          fi
 
       - name: Download Qt install artifact
         uses: actions/download-artifact@v4
         with:
-          name: ${{ env.QT_ARTIFACT_NAME }}
-          path: ${{ env.QT_INSTALL_DIR }}
+          name: "qt-install-linux"
+          path: ${{ needs.build-qt-static-linux.outputs.qt-install-dir }}
 
-      - name: Install system dependencies (Linux)
-        if: matrix.os == 'ubuntu-latest'
+      - name: Install additional dependencies
         run: |
           sudo apt-get update
-          sudo apt-get install -y \
+          sudo apt-get install -y build-essential perl python3 cmake ninja-build git \
             libgl1-mesa-dev libfontconfig1-dev libfreetype6-dev \
             libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev \
             libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev \
             libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev \
             libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev \
-            libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev \
-            libpcre2-dev libdbus-1-dev libpng-dev libjpeg-dev libglib2.0-dev
-
-      - name: Build Squiggle (Linux)
-        if: matrix.os == 'ubuntu-latest'
+            libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev dbus-x11 \
+            libpcre2-dev libdbus-1-dev libpng-dev libjpeg-dev libglib2.0-dev \
+            python3 gperf bison flex libwayland-dev wayland-protocols
         shell: bash
+
+      - name: Build unixcaptool
+        env:
+          QT_INSTALL_DIR: ${{ needs.build-qt-static-linux.outputs.qt-install-dir }}
         run: |
           export PATH="${{ env.QT_INSTALL_DIR }}/bin:$PATH"
           export PKG_CONFIG_PATH="${{ env.QT_INSTALL_DIR }}/lib/pkgconfig:$PKG_CONFIG_PATH"
+          
+          echo "Setting execute permissions for Qt binaries..."
           chmod -R +x ${QT_INSTALL_DIR}/bin
           chmod -R +x ${QT_INSTALL_DIR}/libexec
+          cd packages/unixcaptool
           
-          cd packages/squiggle
-          
-          qmake CONFIG+=static "QTPLUGIN+=${{ matrix.platform-plugin }}" "QTPLUGIN+=qpng" squiggle.pro
+          qmake CONFIG+=static build.linux.pro
           
           make -j$(nproc)
           mkdir -p dist
-          cp squiggle dist/
-          strip dist/squiggle
-
-      - name: Build Squiggle (Windows)
-        if: matrix.os == 'windows-latest'
-        shell: cmd
-        run: |
-          set "PATH=${{ env.QT_INSTALL_DIR }}\bin;%PATH%"
+          cp unixcaptool dist/
           
-          cd packages\squiggle
+          echo "Stripping binary..."
+          strip dist/unixcaptool
           
-          qmake CONFIG+=static "QTPLUGIN+=${{ matrix.platform-plugin }}" "QTPLUGIN+=qpng" squiggle.pro
-          
-          ninja
-          
-          mkdir dist
-          copy release\squiggle.exe dist\squiggle.exe
-
-      - name: Build Squiggle (macOS)
-        if: matrix.os == 'macos-latest'
+          rm unixcaptool
         shell: bash
-        run: |
-          export PATH="${{ env.QT_INSTALL_DIR }}/bin:$PATH"
-          
-          cd packages/squiggle
-          
-          qmake CONFIG+=static "QTPLUGIN+=${{ matrix.platform-plugin }}" "QTPLUGIN+=qpng" squiggle.pro
-          
-          make -j$(sysctl -n hw.ncpu)
-          
-          mkdir -p dist
-          cp squiggle.app/Contents/MacOS/squiggle dist/
-          strip dist/squiggle
 
-      - name: Upload Final Artifact
+      - name: Verify static linking (check that Qt is not dynamic)
+        run: |
+          # This test checks that the executable is NOT linked to any libQt*.so files.
+          ldd packages/unixcaptool/dist/unixcaptool | grep libQt && (echo "Error: unixcaptool is dynamically linked to Qt"; exit 1) || echo "Success: unixcaptool is statically linked to Qt"
+        shell: bash
+
+      - name: Upload artifact
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ matrix.artifact-name }}
-          path: ${{ matrix.binary-path }}
+          name: unixcaptool-linux
+          path: packages/unixcaptool/dist/unixcaptool
+
+  build-unixcaptool-macos:
+    needs: build-qt-macos
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Download Qt install artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: "qt-install-macos"
+          path: ${{ needs.build-qt-macos.outputs.qt-install-dir }}
+
+      - name: Build unixcaptool
+        env:
+          QT_INSTALL_DIR: ${{ needs.build-qt-macos.outputs.qt-install-dir }}
+        run: |
+          export PATH="${{ env.QT_INSTALL_DIR }}/bin:$PATH"
+          export PKG_CONFIG_PATH="${{ env.QT_INSTALL_DIR }}/lib/pkgconfig:$PKG_CONFIG_PATH"
+          
+          echo "Setting execute permissions for Qt binaries..."
+          chmod -R +x ${QT_INSTALL_DIR}/bin
+          chmod -R +x ${QT_INSTALL_DIR}/libexec
+          cd packages/unixcaptool
+          
+          qmake CONFIG+=static build.darwin.pro
+          
+          make -j$(sysctl -n hw.ncpu)
+          mkdir -p dist
+          cp unixcaptool dist/
+          
+          rm unixcaptool
+        shell: bash
+
+      - name: Verify static linking (otool check)
+        run: |
+          # Check no dynamic Qt libs
+          otool -L packages/unixcaptool/dist/unixcaptool | grep Qt || echo "Success: No dynamic Qt libs linked"
+        shell: bash
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: unixcaptool-macos
+          path: packages/unixcaptool/dist/unixcaptool
