Add CI for CAPKIT

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -1,7 +1,8 @@
 name: Build macOS
 
 on:
-  workflow_dispatch:
+  # workflow_dispatch:
+  push:
     
 jobs:
   build:
@@ -34,19 +35,19 @@ jobs:
       working-directory: packages/capturekit
       run: bash ./PKGBUILD
 
-    - name: Zip dist directory
+    - name: Create distribution zip
       working-directory: packages/capturekit
       run: |
-        if [ -d dist ]; then
-          zip -r dist.zip dist
+        if [ -d "dist" ]; then
+          mv dist capkit-macos
+          zip -r capkit-macos.zip capkit-macos
         else
-          echo "dist directory not found; creating empty zip to avoid failure"
-          mkdir -p dist
-          zip -r dist.zip dist
+          echo "dist directory not found, skipping zip."
+          exit 1
         fi
 
     - name: Upload dist artifact
       uses: actions/upload-artifact@v4
       with:
         name: capkit-macos
-        path: packages/capturekit/dist.zip
+        path: packages/capturekit/capkit-macos.zip
